# Generated by Django 5.1.9 on 2026-01-02 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("matricule", models.CharField(max_length=50, unique=True)),
                ("age", models.IntegerField()),
                ("gender", models.CharField(max_length=20)),
                ("department", models.CharField(max_length=100)),
                ("job_title", models.CharField(max_length=120)),
                ("seniority_years", models.FloatField()),
                ("contract_type", models.CharField(max_length=50)),
                ("leave_balance", models.FloatField()),
                ("team_size", models.IntegerField()),
                ("nb_previous_requests", models.IntegerField(default=0)),
                ("nb_accepted_before", models.IntegerField(default=0)),
                ("nb_refused_before", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="LeaveRequest",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("duration_days", models.IntegerField()),
                ("leave_type", models.CharField(max_length=50)),
                ("leave_reason", models.CharField(max_length=120)),
                ("month", models.IntegerField()),
                ("is_peak_period", models.IntegerField(default=0)),
                ("manager_approval", models.IntegerField(default=0)),
                ("overlapping_team_leaves", models.IntegerField(default=0)),
                ("rules_violation_flag", models.IntegerField(default=0)),
                ("accepted", models.BooleanField(blank=True, null=True)),
                ("confidence", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="conges.employee",
                    ),
                ),
            ],
        ),
    ]
