# Generated by Django 6.0 on 2026-01-07 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conges", "0002_employee_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaverequest",
            name="features_sent",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="leaverequest",
            name="model_version",
            field=models.CharField(default="rf_leave_v1", max_length=50),
        ),
        migrations.AddField(
            model_name="leaverequest",
            name="raw_payload",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="leaverequest",
            name="duration_days",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="leaverequest",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="leave_requests",
                to="conges.employee",
            ),
        ),
        migrations.AlterField(
            model_name="leaverequest",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="leaverequest",
            name="is_peak_period",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="leaverequest",
            name="leave_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="leaverequest",
            name="manager_approval",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="leaverequest",
            name="month",
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name="leaverequest",
            name="overlapping_team_leaves",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="leaverequest",
            name="rules_violation_flag",
            field=models.BooleanField(default=False),
        ),
    ]
