# Generated by Django 5.1.9 on 2026-01-07 22:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conges", "0003_leaverequest_features_sent_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="leaverequest",
            name="decided_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="leaverequest",
            name="decided_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="decided_leave_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="leaverequest",
            name="hr_comment",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="leaverequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("PREDICTED", "Prédit par IA"),
                    ("VALIDATED", "Validé par RH"),
                    ("REJECTED_BY_RH", "Refusé par RH"),
                ],
                default="PREDICTED",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="leaverequest",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
